### ISSUE TITLE
Math AutoCorrect Codes on Support Pages Are Improperly Being Translated into Other Languages

### ISSUE THREAD

**Issue by brichwin** [daisy/math-a11y#52]
When the [Linear format equations using UnicodeMath and LaTeX in Word](https://support.microsoft.com/en-us/office/linear-format-equations-using-unicodemath-and-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8) support page is automatically translated to another language, the Math AutoCorrect codes listed as text change (are translated) as well. However, these codes only work in their original English form. Thus, when auto-translated to another language, most of the listed Math AutoCorrect codes are incorrect. 

For example, this section from the [“en-US” rendering](https://support.microsoft.com/en-us/office/linear-format-equations-using-unicodemath-and-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8):
![Table showing English AutoCorrect codes for math symbols: \bowtie, \box, \bra](https://github.com/user-attachments/assets/f46fb710-bb3e-4f9c-a807-4c909db09acb)

Becomes the following in the [“it-it” rendering](https://support.microsoft.com/it-it/office/equazioni-in-formato-lineare-che-usano-unicodemath-e-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8). Note how some codes now even include spaces:
![Table showing Italian translation of AutoCorrect codes where symbols remain the same but commands are mistakenly translated: \bowtie became \cravatta a farfalla, \box became \scatola, and \bra became \reggiseno"](https://github.com/user-attachments/assets/dc996a51-fa55-46ce-9a1a-fb724a524381)

**Comment by jenmarsala** [comment]
I confirm that this issue exists as described.

**Comment by petewu100** [comment]
For the UnicodeMath and LaTeX help article in Italian, https://support.microsoft.com/it-it/office/equazioni-in-formato-lineare-che-usano-unicodemath-e-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8, the codes are not showing as translated currently:

⋈ | Join naturale | \bowtie
-- | -- | --

Perhaps the issue has been fixed.

@brichwin @jenmarsala can you take a look at the latest version of the UnicodeMath and LaTeX help article in a few languages and let us know if you spot any translated codes?

Regarding the Math AutoCorrect codes article: I also see that translations for the page are not available, so it is always loading in English. We should try that in a separate bug report.

Thank you.

**Comment by jenmarsala** [comment]
I believe that this issue still exists at [Linear format equations using UnicodeMath and LaTeX in Word].(https://support.microsoft.com/en-us/office/linear-format-equations-using-unicodemath-and-latex-in-word-2e00618d-b1fd-49d8-8cb4-8d17f25754f8)
@petewu100 I tried four different languages and am still seeing some codes that are being translated to different languages. Screenshots of Arabic, French, German, and Italian are below. (My apologies that I missed your request when originally posted!)

![Arabic translation - 3 of the first 7 AutoCorrect codes are translated to Arabic](https://github.com/user-attachments/assets/2228bc9e-c727-471c-90f9-680174f4c770)
![French translation - 1 of the first 7 AutoCorrect codes is translated to French; 3 others in English have the first letter capitalized](https://github.com/user-attachments/assets/ec34916c-17a6-4579-9345-ddbeb4f1f5fb)
![German translation - 2 of the first 7 AutoCorrect codes are translated to German; one is in English but has the first letter capitalized](https://github.com/user-attachments/assets/27859716-546e-4005-a16c-a817070ac252)
![Italian translation - 1 of the first 7 Autocorrect codes is translated to Italian; 2 others in English have the first letter capitalized](https://github.com/user-attachments/assets/e85adf41-2679-4464-82ee-fd305352db61)
